require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/movimientos", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Movimiento. As you add validations to Movimiento, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Movimiento.create! valid_attributes
      get movimientos_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      movimiento = Movimiento.create! valid_attributes
      get movimiento_url(movimiento)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_movimiento_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      movimiento = Movimiento.create! valid_attributes
      get edit_movimiento_url(movimiento)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Movimiento" do
        expect {
          post movimientos_url, params: { movimiento: valid_attributes }
        }.to change(Movimiento, :count).by(1)
      end

      it "redirects to the created movimiento" do
        post movimientos_url, params: { movimiento: valid_attributes }
        expect(response).to redirect_to(movimiento_url(Movimiento.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Movimiento" do
        expect {
          post movimientos_url, params: { movimiento: invalid_attributes }
        }.to change(Movimiento, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post movimientos_url, params: { movimiento: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested movimiento" do
        movimiento = Movimiento.create! valid_attributes
        patch movimiento_url(movimiento), params: { movimiento: new_attributes }
        movimiento.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the movimiento" do
        movimiento = Movimiento.create! valid_attributes
        patch movimiento_url(movimiento), params: { movimiento: new_attributes }
        movimiento.reload
        expect(response).to redirect_to(movimiento_url(movimiento))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        movimiento = Movimiento.create! valid_attributes
        patch movimiento_url(movimiento), params: { movimiento: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested movimiento" do
      movimiento = Movimiento.create! valid_attributes
      expect {
        delete movimiento_url(movimiento)
      }.to change(Movimiento, :count).by(-1)
    end

    it "redirects to the movimientos list" do
      movimiento = Movimiento.create! valid_attributes
      delete movimiento_url(movimiento)
      expect(response).to redirect_to(movimientos_url)
    end
  end
end
