# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

ADMIN_EMAIL: support@ABCLTDA.com
COMPANY_NAME: ABCLTDA
POSTMARK_API_TOKEN: xxxx-yyy-zzzz

development:
  BASE_URL: http://localhost:3000
  DB_USERNAME: "cast3"
  DB_PASSWORD: "'0124'"
  DB_NAME: "ABCLTDA_development"
  DB_POOL: "5"
