default: &default
  adapter: postgresql
  encoding: unicode
  username: cast3
  password: '0124'
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ABCLTDA_development

test:
  <<: *default
  database: ABCLTDA_test
  
production:
  <<: *default
  database: ABCLTDA_production
  username: ABCLTDA
  password: <%= ENV["ABCLTDA_DATABASE_PASSWORD"] %>
